name: CI

on:
  push:
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run tests
        run: make test
